create table if not exists player_characters (
    id bigserial primary key,
    owner_user_id bigint not null references users(id) on delete cascade,
    system_code varchar(32) not null default 'dnd5e',
    name varchar(160) not null,
    status varchar(20) not null default 'DRAFT',
    portrait_url text,
    race_name varchar(120) not null default '',
    subrace_name varchar(120) not null default '',
    class_name varchar(120) not null default '',
    subclass_name varchar(120) not null default '',
    background_name varchar(120) not null default '',
    alignment varchar(80) not null default '',
    level integer not null default 1,
    experience_points integer not null default 0,
    ability_mode varchar(20) not null default 'MANUAL',
    strength integer not null default 10,
    dexterity integer not null default 10,
    constitution integer not null default 10,
    intelligence integer not null default 10,
    wisdom integer not null default 10,
    charisma integer not null default 10,
    max_hp integer not null default 1,
    current_hp integer not null default 1,
    temp_hp integer not null default 0,
    armor_class integer not null default 10,
    initiative_bonus integer not null default 0,
    speed integer not null default 30,
    proficiency_bonus integer not null default 2,
    hit_dice varchar(60) not null default '',
    skill_notes text not null default '',
    saving_throw_notes text not null default '',
    equipment_notes text not null default '',
    feature_notes text not null default '',
    personality_notes text not null default '',
    private_notes text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_player_characters_owner on player_characters(owner_user_id);
create index if not exists idx_player_characters_system on player_characters(system_code);
