-- V16__add_swade_and_alien_rules.sql
-- Zasady dla Savage Worlds Adventure Edition (SWADE) i Alien RPG

-- =========================
-- SAVAGE WORLDS (swade)
-- =========================

INSERT INTO rules_pages (system_code, slug, title, content) VALUES

('swade', 'podstawy-systemu', 'Podstawy systemu', 'Savage Worlds to system RPG zaprojektowany pod hasłem "Fast! Furious! Fun!" — szybka, dynamiczna rozgrywka bez zbędnych przestojów.\n\nKluczowe cechy systemu:\n- Karty Inicjatywy: zamiast rzutów, inicjatywa jest losowana kartami z talii (asy i joker dają premie).\n- Karby (Bennies): żetony umożliwiające powtarzanie rzutów, absorbowanie obrażeń lub inne efekty. Standardowo gracz zaczyna z 3.\n- Postacie Dzikie (Wild Cards): bohaterowie graczy i ważne NPC — rzucają dodatkową "Dziką Kością" (k6) i wybierają lepszy wynik.\n- Zbiry (Extras): szeregowi przeciwnicy — bez Dzikiej Kości, padają od jednego trafienia z podniesionym poziomem sukcesu.'),

('swade', 'rzuty-i-sukcesy', 'Rzuty i sukcesy', 'Rzuty w SWADE:\n- Rzucasz odpowiednią kością Atrybutu lub Umiejętności (k4, k6, k8, k10, k12).\n- Jako Dzika Karta rzucasz również k6 i wybierasz wyższy wynik.\n- Trudność standardowa: 4.\n- Sukces = wynik ≥ 4. Każde pełne 4 powyżej progu to Podniesienie (Raise), dające dodatkowy efekt.\n\nAsy (Acing):\n- Gdy na kości wypada jej maksimum (np. 6 na k6), rzucasz jeszcze raz i dodajesz do wyniku. Można wielokrotnie.\n\nModyfikatory:\n- Przeszkody, zranienie, warunki: modyfikatory od -1 do -4 lub więcej.\n- Atakowanie Zbiorów (Group Attack): -2 do ataku przy ostrzale kilku celów.'),

('swade', 'walka', 'Walka', 'Kolejność akcji wyznacza talia kart — każdy uczestnik walki dobiera kartę na początku rundy:\n- Wyższa karta = pierwszeństwo (As > K > D > W > 10 ... 2).\n- Kolor określa kolejność przy remisie (piki, kiery, kara, trefle).\n- Joker: możesz działać w dowolnym momencie rundy i dostajesz +2 do wszystkich rzutów.\n\nAkcje w turze:\n- Akcja (Action): atak, rzucanie czaru, aktywowanie zdolności.\n- Ruch (Movement): postać może poruszać się o SW w swoim Tempie (zwykle 6″).\n- Wolna Akcja: drobne czynności nie wymagające rzutu.\n\nAtaki i obrażenia:\n- Atak Wręcz / Broń palna: Walka vs Parry (cel) lub zwykły rzut vs trudność 4.\n- Obrażenia: rzut kością obrażeń broni + Siła (wręcz). Wynik vs Wytrzymałość (Toughness).'),

('swade', 'obrenia-i-rankingi', 'Obrażenia i kondycja', 'Wytrzymałość (Toughness) = 2 + połowa Wigoru (Vigor) + ewentualna zbroja.\n\nProgi obrażeń:\n- Wynik obrażeń < Wytrzymałość: żadnego efektu.\n- ≥ Wytrzymałość: Ogłuszony (Shaken) — postać traci akcję, może tylko odzyskać przytomność lub się poruszać.\n- Podniesienie powyżej Wytrzymałości: Rana (Wound) — kara -1 do wszystkich rzutów (kumuluje się).\n\nDzika Karta może mieć max 3 Rany — przy 4. wypada z walki (nieprzytomna lub martwa, zależnie od narracji).\n\nOdnowa po walce:\n- Test Wigoru lub opieka medyczna (Healing) usuwa Rany.\n- Ogłuszenie odpada po udanym teście Ducha (Spirit) na początku tury.'),

('swade', 'zdolnosci-i-atuty', 'Zdolności i Atuty', 'Atrybuty (5 sztuk): Agility, Smarts, Spirit, Strength, Vigor — na skali k4 → k12.\nUmiejętności: powiązane z atrybutami; rzucasz kością Umiejętności (lub k4 jeśli jej nie masz).\n\nAtuty (Edges):\n- Zdobywane na starcie i przy awansach.\n- Wymagają zazwyczaj określonego ranku (Nowicjusz, Doświadczony, Weteran, Bohater, Legenda).\n- Przykłady: Tough as Nails (+1 Wytrzymałość), Frenzy (dwa ataki wręcz), Marksman (+2 do ataków dystansowych po braku ruchu).\n\nAwanse (Advances):\n- Co 5 XP postać dostaje Awans.\n- Awans = podnieś Umiejętność, zdobądź Atut lub zwiększ Atrybut (raz na 2 awanse).'),

('swade', 'magiczne-systemy', 'Magia i moce', 'W SWADE nie ma jednego systemu magii — zamiast tego istnieją "Arkaniczne Zaplecza" (Arcane Backgrounds):\n- Magia (Magic): tradycyjny czarownik.\n- Cuda (Miracles): kapłan lub wyznawca.\n- Psychika (Psionics): moce mentalne.\n- Super Moce (Super Powers): bohaterowie komiksowi.\n\nMoce kosztują Punkty Mocy (Power Points, PP). Rzucasz Arcaną (Arcane skill) vs trudność 4.\n- Sukces: moc działa normalnie.\n- Raise: wzmocniony efekt.\n- Porażka: PP stracone, moc nie działa.\n- 1 na kości Arcany: Backfire — efekt uboczny.\n\nPunkty Mocy odnawiają się w tempie 1 PP/godz. lub szybciej dzięki specjalnym zdolnościom.');

-- =========================
-- ALIEN RPG (alien)
-- =========================

INSERT INTO rules_pages (system_code, slug, title, content) VALUES

('alien', 'podstawy-systemu', 'Podstawy systemu', 'Alien RPG to gra oparta na silniku Year Zero Engine, osadzona w oficjalnym kanonie filmów Alien. Klimat: horror survivalowy, kosmiczny terror, paranoja i człowiek jako najsłabsze ogniwo.\n\nCentrum mechaniki: rzuty pulą kości k6.\n- Rzucasz liczbą k6 równą wartości Atrybutu + Umiejętności.\n- Cel: uzyskać co najmniej jedną szóstkę.\n- Każda dodatkowa szóstka to Atut (Push) — dodatkowy efekt.\n\nDwa tryby gry:\n- Tryb Korytarza (Cinematic): jednorazowe, intensywne sesje z gotowymi agendami i ukrytymi celami dla graczy. Wysoka śmiertelność.\n- Tryb Kampanii (Campaign): standardowe, dłuższe sesje, nastawione na przetrwanie i eksplorację.'),

('alien', 'rzuty-i-pula-kosci', 'Rzuty i pula kości', 'Pula kości = Atrybut + Umiejętność (+ ewentualne modyfikatory).\n- Minimalna pula: 1k6.\n- Maksymalna pula: zalecane 10k6.\n\nWynik:\n- ≥1 szóstka: sukces.\n- Każda dodatkowa szóstka: Atut — możesz wybrać efekty z listy dla danej umiejętności.\n- 0 szóstek: porażka.\n\nPush (Popychanie):\n- Możesz powtórzyć nieudany rzut raz.\n- Rzucasz ponownie wszystkimi kośćmi BEZ szóstek z poprzedniego rzutu.\n- Każda jedynka (1) w łącznym wyniku Push-a zwiększa Poziom Stresu o 1.\n\nKości Paniki:\nGdy Stres jest wysoki, rzucasz Kością Paniki (k6) — wynik ≤ aktualnemu Stresowi wywołuje Panikę, której efekt losowany jest z tabeli.'),

('alien', 'stres-i-panika', 'Stres i Panika', 'Stres (Stress Level) to kluczowy zasób survivalowy:\n- Zaczyna się od 0.\n- Wzrasta przy: Push-owaniu rzutów, traumatycznych wydarzeniach, śmierci towarzyszy, obecności Obcego.\n- Spada przy: odpoczynku, medytacji, pomyślnym zakończeniu niebezpiecznych sytuacji.\n\nTest Paniki:\n- Wykonywany gdy Stres > 0 i dochodzi do Pushowania lub specjalnych triggerów.\n- Rzucasz k6 — jeśli wynik ≤ Poziom Stresu → Panika.\n\nTabela Paniki (k6 + Stres):\n2-6: Drżenie — kara -1 do następnego rzutu.\n7-8: Strach — upuszczasz ekwipunek lub krzyczysz.\n9-10: Ucieczka — musisz natychmiast uciec od źródła strachu.\n11-12: Katatoniczny bezruch — nie możesz nic zrobić przez jedną rundę.\n13+: Frenezja — niekontrolowany atak na najbliższą postać.\n\nPanika jest zaraźliwa — inni gracze w pobliżu testują Panikę przy wyniku 10+.'),

('alien', 'walka-i-przetrwanie', 'Walka i przetrwanie', 'Inicjatywa:\n- Rzucasz Sprawnością (Agility) — wyższy wynik działa pierwszy.\n- W przypadku remisu: atakujący ma pierwszeństwo.\n\nAkcje w turze:\n- Szybka Akcja: strzał, ruch o 10m, wyjęcie broni.\n- Powolna Akcja: atak wręcz, pierwsza pomoc, interakcja ze sprzętem.\n- Postać może wykonać jedną Szybką i jedną Powolną akcję na turę.\n\nObrażenia i zdrowie:\n- Zdrowie = Wytrzymałość (Strength). Przy 0 HP → Złamany (Broken), wypadasz z walki.\n- Krytyczne obrażenia: każdy atak, który zabiera ostatnie HP, może spowodować losowy efekt krytyczny (k6 + tabela).\n- Obrażenia broni: pistolet 1k6, karabin 2k6, strzelba 3k6 (blisko).\n\nEkwipunek survivalowy:\n- Kombinezon EVA: ochrona przed próżnią i utratą ciśnienia.\n- Miotacz ognia: 3k6 obrażeń, ale uwaga na płomienie w ciasnych korytarzach.'),

('alien', 'obcy-i-zagroenia', 'Ksenomofrfy i zagrożenia', 'Ksenomorf (Xenomorph):\n- Nie można ich zranić standardową bronią bez Kości Paniki.\n- Każda konfrontacja twarzą w twarz: test Paniki lub Stresu +2.\n- Kwas: gdy Obcy ginie, kwas tryska w zasięgu 1m — obrażenia 1k6 za turę kontaktu.\n- Wykrywanie: ruch na peryferiach wzroku, stukanie w ściany, shadow play — sygnały ostrzegawcze dla MG.\n\nFace Hugger:\n- Atak: Sprawność vs Sprawność. Sukces = przytwierdzenie do twarzy.\n- Niemożliwy do usunięcia bez specjalnego sprzętu lub operacji.\n- Po czasie: implantacja embrionu.\n\nZasady atmosfery i środowiska:\n- Próżnia: bez kombinezonu → 1k6 obrażeń/runda, od 3. rundy → krytyczne.\n- Temperatura: skrajny ziąb lub żar → +1 Stres/scena bez ochrony.\n- Ciemność: -2 do rzutów na percepcję i walkę w ciemnościach.');
