-- TTRPG Assistant consolidated schema migration.
-- Replaces historical V1-V95 chain for new local installations.

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: campaign_characters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaign_characters (
    campaign_id bigint NOT NULL,
    character_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id bigint NOT NULL,
    role character varying(30) DEFAULT 'PLAYER_CHARACTER'::character varying NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    assigned_at timestamp with time zone DEFAULT now() NOT NULL,
    removed_at timestamp with time zone,
    CONSTRAINT chk_campaign_characters_role CHECK (((role)::text = ANY ((ARRAY['PLAYER_CHARACTER'::character varying, 'NPC'::character varying, 'GUEST'::character varying])::text[])))
);


--
-- Name: campaign_materials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaign_materials (
    id bigint NOT NULL,
    campaign_id bigint NOT NULL,
    type character varying(40) NOT NULL,
    title character varying(200) NOT NULL,
    content text DEFAULT ''::text NOT NULL,
    created_by_user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: campaign_materials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.campaign_materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: campaign_materials_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.campaign_materials_id_seq OWNED BY public.campaign_materials.id;


--
-- Name: campaign_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaign_members (
    campaign_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role character varying(20) DEFAULT 'player'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: campaign_notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaign_notifications (
    id bigint NOT NULL,
    campaign_id bigint NOT NULL,
    user_id bigint NOT NULL,
    type character varying(40) NOT NULL,
    message text NOT NULL,
    read_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: campaign_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.campaign_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: campaign_notifications_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.campaign_notifications_id_seq OWNED BY public.campaign_notifications.id;


--
-- Name: campaign_player_notes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaign_player_notes (
    id bigint NOT NULL,
    campaign_id bigint NOT NULL,
    user_id bigint NOT NULL,
    title character varying(160) NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: campaign_player_notes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.campaign_player_notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campaign_player_notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campaign_session_attendance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaign_session_attendance (
    session_id bigint NOT NULL,
    user_id bigint NOT NULL,
    status character varying(20) DEFAULT 'MAYBE'::character varying NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    id bigint NOT NULL,
    campaign_id bigint NOT NULL,
    note text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT campaign_session_attendance_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'MAYBE'::character varying, 'UNAVAILABLE'::character varying])::text[])))
);


--
-- Name: campaign_session_attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.campaign_session_attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campaign_session_attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campaign_session_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaign_session_messages (
    id bigint NOT NULL,
    session_id bigint NOT NULL,
    author_user_id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: campaign_session_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.campaign_session_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: campaign_session_messages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.campaign_session_messages_id_seq OWNED BY public.campaign_session_messages.id;


--
-- Name: campaign_session_notes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaign_session_notes (
    session_id bigint NOT NULL,
    summary text DEFAULT ''::text NOT NULL,
    important_events text DEFAULT ''::text NOT NULL,
    loot text DEFAULT ''::text NOT NULL,
    npc_refs text DEFAULT ''::text NOT NULL,
    decisions text DEFAULT ''::text NOT NULL,
    next_hooks text DEFAULT ''::text NOT NULL,
    updated_by_user_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: campaign_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaign_sessions (
    id bigint NOT NULL,
    campaign_id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description_md text DEFAULT ''::text NOT NULL,
    status character varying(20) DEFAULT 'PLANNED'::character varying NOT NULL,
    scheduled_for timestamp with time zone,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    created_by_user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_campaign_sessions_status CHECK ((upper((status)::text) = ANY (ARRAY['PLANNED'::text, 'IN_PROGRESS'::text, 'FINISHED'::text])))
);


--
-- Name: campaign_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.campaign_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: campaign_sessions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.campaign_sessions_id_seq OWNED BY public.campaign_sessions.id;


--
-- Name: campaigns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaigns (
    id bigint NOT NULL,
    owner_user_id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description_md text DEFAULT ''::text NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    system_code character varying(32) DEFAULT 'dnd5e'::character varying NOT NULL,
    join_code character varying(20) NOT NULL,
    cover_image_url text,
    visibility character varying(20) DEFAULT 'PRIVATE'::character varying NOT NULL,
    player_limit integer DEFAULT 5 NOT NULL,
    banner_image_url text,
    CONSTRAINT chk_campaigns_status CHECK ((lower((status)::text) = ANY (ARRAY['active'::text, 'finished'::text, 'archived'::text])))
);


--
-- Name: campaigns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.campaigns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: campaigns_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.campaigns_id_seq OWNED BY public.campaigns.id;


--
--



--
-- Name: combat_encounters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.combat_encounters (
    id bigint NOT NULL,
    campaign_id bigint NOT NULL,
    session_id bigint,
    name character varying(160) NOT NULL,
    system_code character varying(40) NOT NULL,
    status character varying(30) DEFAULT 'ACTIVE'::character varying NOT NULL,
    current_turn_index integer DEFAULT 0 NOT NULL,
    round_number integer DEFAULT 1 NOT NULL,
    created_by_user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT chk_combat_encounters_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'FINISHED'::character varying, 'ARCHIVED'::character varying])::text[])))
);


--
-- Name: combat_encounters_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.combat_encounters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: combat_encounters_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.combat_encounters_id_seq OWNED BY public.combat_encounters.id;


--
-- Name: combat_participants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.combat_participants (
    id bigint NOT NULL,
    encounter_id bigint NOT NULL,
    character_id bigint,
    name character varying(160) NOT NULL,
    participant_type character varying(30) NOT NULL,
    initiative_value integer NOT NULL,
    initiative_modifier integer,
    sort_order integer DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    is_defeated boolean DEFAULT false NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    max_hp integer,
    current_hp integer,
    temp_hp integer DEFAULT 0 NOT NULL,
    armor_class integer,
    conditions text,
    death_save_successes integer DEFAULT 0 NOT NULL,
    death_save_failures integer DEFAULT 0 NOT NULL,
    CONSTRAINT chk_combat_participants_armor_class CHECK (((armor_class IS NULL) OR (armor_class >= 0))),
    CONSTRAINT chk_combat_participants_current_hp CHECK (((current_hp IS NULL) OR (current_hp >= 0))),
    CONSTRAINT chk_combat_participants_death_save_failures CHECK (((death_save_failures >= 0) AND (death_save_failures <= 3))),
    CONSTRAINT chk_combat_participants_death_save_successes CHECK (((death_save_successes >= 0) AND (death_save_successes <= 3))),
    CONSTRAINT chk_combat_participants_max_hp CHECK (((max_hp IS NULL) OR (max_hp >= 0))),
    CONSTRAINT chk_combat_participants_temp_hp CHECK ((temp_hp >= 0)),
    CONSTRAINT chk_combat_participants_type CHECK (((participant_type)::text = ANY ((ARRAY['PLAYER_CHARACTER'::character varying, 'NPC'::character varying, 'MONSTER'::character varying, 'CUSTOM'::character varying])::text[])))
);


--
-- Name: combat_participants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.combat_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: combat_participants_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.combat_participants_id_seq OWNED BY public.combat_participants.id;


--
-- Name: dice_rolls; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dice_rolls (
    id bigint NOT NULL,
    campaign_id bigint NOT NULL,
    session_id bigint,
    encounter_id bigint,
    participant_id bigint,
    character_id bigint,
    rolled_by_user_id bigint NOT NULL,
    roll_label character varying(160),
    roll_expression character varying(120) NOT NULL,
    roll_type character varying(40) DEFAULT 'GENERIC'::character varying NOT NULL,
    total integer NOT NULL,
    dice_results text NOT NULL,
    modifier integer DEFAULT 0 NOT NULL,
    is_private boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT dice_rolls_roll_type_check CHECK (((roll_type)::text = ANY ((ARRAY['GENERIC'::character varying, 'ATTACK'::character varying, 'DAMAGE'::character varying, 'SAVE'::character varying, 'SKILL'::character varying, 'INITIATIVE'::character varying, 'CUSTOM'::character varying])::text[])))
);


--
-- Name: dice_rolls_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dice_rolls ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dice_rolls_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dm_conversation_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dm_conversation_members (
    conversation_id bigint NOT NULL,
    user_id bigint NOT NULL,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    muted boolean DEFAULT false NOT NULL,
    joined_at timestamp with time zone DEFAULT now() NOT NULL,
    last_read_message_id bigint,
    last_read_at timestamp with time zone
);


--
-- Name: dm_conversations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dm_conversations (
    id bigint NOT NULL,
    type character varying(20) DEFAULT 'DIRECT'::character varying NOT NULL,
    direct_key character varying(80),
    title character varying(180) DEFAULT ''::character varying NOT NULL,
    created_by_user_id bigint NOT NULL,
    last_message_preview character varying(280) DEFAULT ''::character varying NOT NULL,
    last_message_sender_user_id bigint,
    last_message_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: dm_conversations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.dm_conversations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: dm_conversations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.dm_conversations_id_seq OWNED BY public.dm_conversations.id;


--
-- Name: dm_message_attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dm_message_attachments (
    id bigint NOT NULL,
    message_id bigint NOT NULL,
    uploader_user_id bigint NOT NULL,
    storage_path character varying(500) NOT NULL,
    original_name character varying(255) NOT NULL,
    mime_type character varying(120) NOT NULL,
    size_bytes bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: dm_message_attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.dm_message_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: dm_message_attachments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.dm_message_attachments_id_seq OWNED BY public.dm_message_attachments.id;


--
-- Name: dm_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dm_messages (
    id bigint NOT NULL,
    conversation_id bigint NOT NULL,
    sender_user_id bigint NOT NULL,
    content text DEFAULT ''::text NOT NULL,
    attachment_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    edited_at timestamp with time zone,
    deleted_at timestamp with time zone
);


--
-- Name: dm_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.dm_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: dm_messages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.dm_messages_id_seq OWNED BY public.dm_messages.id;


--
-- Name: friend_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.friend_requests (
    id bigint NOT NULL,
    sender_user_id bigint NOT NULL,
    receiver_user_id bigint NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    responded_at timestamp with time zone,
    CONSTRAINT chk_friend_requests_status CHECK ((upper((status)::text) = ANY (ARRAY['PENDING'::text, 'ACCEPTED'::text, 'REJECTED'::text, 'CANCELED'::text]))),
    CONSTRAINT chk_friend_requests_users CHECK ((sender_user_id <> receiver_user_id))
);


--
-- Name: friend_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.friend_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: friend_requests_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.friend_requests_id_seq OWNED BY public.friend_requests.id;


--
-- Name: friendships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.friendships (
    user_id bigint NOT NULL,
    friend_user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_friendships_users CHECK ((user_id <> friend_user_id))
);


--
--



--
-- Name: generator_definitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.generator_definitions (
    id bigint NOT NULL,
    code character varying(64) NOT NULL,
    name character varying(120) NOT NULL,
    description character varying(500),
    category character varying(40) NOT NULL,
    icon character varying(48),
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    category_code character varying(50),
    type_code character varying(50),
    genre_tags jsonb DEFAULT '[]'::jsonb,
    system_tags jsonb DEFAULT '[]'::jsonb,
    tone_tags jsonb DEFAULT '[]'::jsonb,
    display_order integer DEFAULT 0,
    icon_key character varying(80)
);


--
-- Name: generator_definitions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.generator_definitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: generator_definitions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.generator_definitions_id_seq OWNED BY public.generator_definitions.id;


--
-- Name: generator_field_definitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.generator_field_definitions (
    id bigint NOT NULL,
    variant_id bigint NOT NULL,
    field_key character varying(80) NOT NULL,
    label character varying(120) NOT NULL,
    type character varying(32) NOT NULL,
    options_json jsonb DEFAULT '[]'::jsonb NOT NULL,
    default_value character varying(200),
    required boolean DEFAULT false NOT NULL,
    order_index integer DEFAULT 0 NOT NULL
);


--
-- Name: generator_field_definitions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.generator_field_definitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: generator_field_definitions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.generator_field_definitions_id_seq OWNED BY public.generator_field_definitions.id;


--
-- Name: generator_pools; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.generator_pools (
    id bigint NOT NULL,
    generator_type character varying(32) NOT NULL,
    system_code character varying(32) NOT NULL,
    payload_json jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    subtype character varying(48) DEFAULT 'default'::character varying NOT NULL
);


--
-- Name: generator_pools_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.generator_pools_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: generator_pools_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.generator_pools_id_seq OWNED BY public.generator_pools.id;


--
-- Name: generator_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.generator_results (
    id bigint NOT NULL,
    user_id bigint,
    campaign_id bigint,
    generator_code character varying(64) NOT NULL,
    variant_code character varying(80) NOT NULL,
    input_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    output_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    title character varying(160) NOT NULL,
    summary character varying(500),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: generator_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.generator_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: generator_results_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.generator_results_id_seq OWNED BY public.generator_results.id;


--
-- Name: generator_variants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.generator_variants (
    id bigint NOT NULL,
    generator_definition_id bigint NOT NULL,
    variant_code character varying(80) NOT NULL,
    system_code character varying(32) DEFAULT 'any'::character varying NOT NULL,
    setting_code character varying(48) DEFAULT 'none'::character varying NOT NULL,
    mode character varying(32) DEFAULT 'quick'::character varying NOT NULL,
    name character varying(120) NOT NULL,
    description character varying(500),
    is_active boolean DEFAULT true NOT NULL,
    category_code character varying(50),
    tone_scope jsonb DEFAULT '[]'::jsonb
);


--
-- Name: generator_variants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.generator_variants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: generator_variants_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.generator_variants_id_seq OWNED BY public.generator_variants.id;


--
-- Name: glossary_terms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.glossary_terms (
    id bigint NOT NULL,
    term_pl character varying(120) NOT NULL,
    term_en character varying(120),
    definition text NOT NULL,
    category character varying(60) NOT NULL,
    system character varying(60) DEFAULT 'uniwersalne'::character varying NOT NULL,
    tags character varying(255) DEFAULT ''::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: glossary_terms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.glossary_terms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: glossary_terms_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.glossary_terms_id_seq OWNED BY public.glossary_terms.id;


--
-- Name: initiative_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.initiative_entries (
    id bigint NOT NULL,
    queue_id bigint NOT NULL,
    entity_type character varying(20) DEFAULT 'custom'::character varying NOT NULL,
    entity_id bigint,
    name character varying(200) NOT NULL,
    initiative integer DEFAULT 0 NOT NULL,
    ac integer,
    hp_max integer,
    hp_current integer,
    state character varying(20) DEFAULT 'active'::character varying NOT NULL,
    state_note character varying(140) DEFAULT ''::character varying NOT NULL,
    note text DEFAULT ''::text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: initiative_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.initiative_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: initiative_entries_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.initiative_entries_id_seq OWNED BY public.initiative_entries.id;


--
-- Name: initiative_queues; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.initiative_queues (
    id bigint NOT NULL,
    owner_user_id bigint NOT NULL,
    campaign_id bigint,
    title character varying(200) DEFAULT 'Inicjatywa'::character varying NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    round_number integer DEFAULT 1 NOT NULL,
    active_index integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: initiative_queues_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.initiative_queues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: initiative_queues_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.initiative_queues_id_seq OWNED BY public.initiative_queues.id;


--
--



--
--



--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    id uuid NOT NULL,
    user_id bigint NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: player_characters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.player_characters (
    id bigint NOT NULL,
    owner_user_id bigint NOT NULL,
    system_code character varying(32) DEFAULT 'dnd5e'::character varying NOT NULL,
    name character varying(160) NOT NULL,
    status character varying(20) DEFAULT 'DRAFT'::character varying NOT NULL,
    portrait_url text,
    race_name character varying(120) DEFAULT ''::character varying NOT NULL,
    subrace_name character varying(120) DEFAULT ''::character varying NOT NULL,
    class_name character varying(120) DEFAULT ''::character varying NOT NULL,
    subclass_name character varying(120) DEFAULT ''::character varying NOT NULL,
    background_name character varying(120) DEFAULT ''::character varying NOT NULL,
    alignment character varying(80) DEFAULT ''::character varying NOT NULL,
    level integer DEFAULT 1 NOT NULL,
    experience_points integer DEFAULT 0 NOT NULL,
    ability_mode character varying(20) DEFAULT 'MANUAL'::character varying NOT NULL,
    strength integer DEFAULT 10 NOT NULL,
    dexterity integer DEFAULT 10 NOT NULL,
    constitution integer DEFAULT 10 NOT NULL,
    intelligence integer DEFAULT 10 NOT NULL,
    wisdom integer DEFAULT 10 NOT NULL,
    charisma integer DEFAULT 10 NOT NULL,
    max_hp integer DEFAULT 1 NOT NULL,
    current_hp integer DEFAULT 1 NOT NULL,
    temp_hp integer DEFAULT 0 NOT NULL,
    armor_class integer DEFAULT 10 NOT NULL,
    initiative_bonus integer DEFAULT 0 NOT NULL,
    speed integer DEFAULT 30 NOT NULL,
    proficiency_bonus integer DEFAULT 2 NOT NULL,
    hit_dice character varying(60) DEFAULT ''::character varying NOT NULL,
    skill_notes text DEFAULT ''::text NOT NULL,
    saving_throw_notes text DEFAULT ''::text NOT NULL,
    equipment_notes text DEFAULT ''::text NOT NULL,
    feature_notes text DEFAULT ''::text NOT NULL,
    personality_notes text DEFAULT ''::text NOT NULL,
    private_notes text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    sheet_json jsonb,
    CONSTRAINT chk_player_characters_status CHECK ((upper((status)::text) = ANY (ARRAY['DRAFT'::text, 'ACTIVE'::text, 'RETIRED'::text])))
);


--
-- Name: player_characters_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.player_characters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: player_characters_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.player_characters_id_seq OWNED BY public.player_characters.id;


--
-- Name: rules_pages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rules_pages (
    id bigint NOT NULL,
    system_code character varying(32) NOT NULL,
    slug character varying(64) NOT NULL,
    title character varying(140) NOT NULL,
    content text NOT NULL,
    category character varying(64) DEFAULT 'reference'::character varying NOT NULL,
    summary character varying(280),
    tags text[] DEFAULT ARRAY[]::text[] NOT NULL,
    quick_ref boolean DEFAULT false NOT NULL,
    sort_order integer DEFAULT 100 NOT NULL,
    source_label character varying(120)
);


--
-- Name: rules_pages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.rules_pages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: rules_pages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.rules_pages_id_seq OWNED BY public.rules_pages.id;


--
-- Name: session_live_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.session_live_state (
    id bigint NOT NULL,
    campaign_id bigint NOT NULL,
    session_id bigint NOT NULL,
    scene_title character varying(160),
    scene_image_url text,
    scene_description text,
    active_encounter_id bigint,
    updated_by_user_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: session_live_state_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.session_live_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_live_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session_player_notes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.session_player_notes (
    id bigint NOT NULL,
    campaign_id bigint NOT NULL,
    session_id bigint NOT NULL,
    user_id bigint NOT NULL,
    title character varying(120) DEFAULT ''::character varying NOT NULL,
    content text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: session_player_notes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.session_player_notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_player_notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
--



--
-- Name: user_blocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_blocks (
    blocker_user_id bigint NOT NULL,
    blocked_user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_user_blocks_users CHECK ((blocker_user_id <> blocked_user_id))
);


--
-- Name: user_campaign_favorites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_campaign_favorites (
    user_id bigint NOT NULL,
    campaign_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: user_notes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_notes (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    title character varying(120) NOT NULL,
    type character varying(20) NOT NULL,
    content text DEFAULT ''::text NOT NULL,
    campaign_id bigint,
    character_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_user_notes_type CHECK (((type)::text = ANY ((ARRAY['SESSION'::character varying, 'NPC'::character varying, 'ITEM'::character varying, 'LORE'::character varying, 'QUEST'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: user_notes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    display_name character varying(120),
    is_mg boolean DEFAULT false NOT NULL,
    username character varying(60) NOT NULL,
    tag_code integer NOT NULL,
    bio text DEFAULT ''::text NOT NULL,
    favorite_system character varying(60) DEFAULT ''::character varying NOT NULL,
    profile_visibility character varying(20) DEFAULT 'PUBLIC'::character varying NOT NULL,
    friends_visibility character varying(20) DEFAULT 'FRIENDS_ONLY'::character varying NOT NULL,
    activity_visibility character varying(20) DEFAULT 'PUBLIC'::character varying NOT NULL,
    last_active_at timestamp with time zone DEFAULT now() NOT NULL,
    chat_nick_color character varying(20) DEFAULT ''::character varying NOT NULL,
    token_invalidated_at timestamp with time zone,
    avatar_url text,
    profile_banner_url text
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: campaign_materials id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_materials ALTER COLUMN id SET DEFAULT nextval('public.campaign_materials_id_seq'::regclass);


--
-- Name: campaign_notifications id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_notifications ALTER COLUMN id SET DEFAULT nextval('public.campaign_notifications_id_seq'::regclass);


--
-- Name: campaign_session_messages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_session_messages ALTER COLUMN id SET DEFAULT nextval('public.campaign_session_messages_id_seq'::regclass);


--
-- Name: campaign_sessions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_sessions ALTER COLUMN id SET DEFAULT nextval('public.campaign_sessions_id_seq'::regclass);


--
-- Name: campaigns id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaigns ALTER COLUMN id SET DEFAULT nextval('public.campaigns_id_seq'::regclass);


--
-- Name: combat_encounters id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_encounters ALTER COLUMN id SET DEFAULT nextval('public.combat_encounters_id_seq'::regclass);


--
-- Name: combat_participants id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_participants ALTER COLUMN id SET DEFAULT nextval('public.combat_participants_id_seq'::regclass);


--
-- Name: dm_conversations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dm_conversations ALTER COLUMN id SET DEFAULT nextval('public.dm_conversations_id_seq'::regclass);


--
-- Name: dm_message_attachments id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dm_message_attachments ALTER COLUMN id SET DEFAULT nextval('public.dm_message_attachments_id_seq'::regclass);


--
-- Name: dm_messages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dm_messages ALTER COLUMN id SET DEFAULT nextval('public.dm_messages_id_seq'::regclass);


--
-- Name: friend_requests id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friend_requests ALTER COLUMN id SET DEFAULT nextval('public.friend_requests_id_seq'::regclass);


--
-- Name: generator_definitions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generator_definitions ALTER COLUMN id SET DEFAULT nextval('public.generator_definitions_id_seq'::regclass);


--
-- Name: generator_field_definitions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generator_field_definitions ALTER COLUMN id SET DEFAULT nextval('public.generator_field_definitions_id_seq'::regclass);


--
-- Name: generator_pools id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generator_pools ALTER COLUMN id SET DEFAULT nextval('public.generator_pools_id_seq'::regclass);


--
-- Name: generator_results id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generator_results ALTER COLUMN id SET DEFAULT nextval('public.generator_results_id_seq'::regclass);


--
-- Name: generator_variants id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generator_variants ALTER COLUMN id SET DEFAULT nextval('public.generator_variants_id_seq'::regclass);


--
-- Name: glossary_terms id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.glossary_terms ALTER COLUMN id SET DEFAULT nextval('public.glossary_terms_id_seq'::regclass);


--
-- Name: initiative_entries id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.initiative_entries ALTER COLUMN id SET DEFAULT nextval('public.initiative_entries_id_seq'::regclass);


--
-- Name: initiative_queues id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.initiative_queues ALTER COLUMN id SET DEFAULT nextval('public.initiative_queues_id_seq'::regclass);


--
-- Name: player_characters id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_characters ALTER COLUMN id SET DEFAULT nextval('public.player_characters_id_seq'::regclass);


--
-- Name: rules_pages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rules_pages ALTER COLUMN id SET DEFAULT nextval('public.rules_pages_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: campaign_characters campaign_characters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_characters
    ADD CONSTRAINT campaign_characters_pkey PRIMARY KEY (campaign_id, character_id);


--
-- Name: campaign_materials campaign_materials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_materials
    ADD CONSTRAINT campaign_materials_pkey PRIMARY KEY (id);


--
-- Name: campaign_members campaign_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_members
    ADD CONSTRAINT campaign_members_pkey PRIMARY KEY (campaign_id, user_id);


--
-- Name: campaign_notifications campaign_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_notifications
    ADD CONSTRAINT campaign_notifications_pkey PRIMARY KEY (id);


--
-- Name: campaign_player_notes campaign_player_notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_player_notes
    ADD CONSTRAINT campaign_player_notes_pkey PRIMARY KEY (id);


--
-- Name: campaign_session_attendance campaign_session_attendance_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_session_attendance
    ADD CONSTRAINT campaign_session_attendance_pk PRIMARY KEY (id);


--
-- Name: campaign_session_attendance campaign_session_attendance_session_user_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_session_attendance
    ADD CONSTRAINT campaign_session_attendance_session_user_unique UNIQUE (session_id, user_id);


--
-- Name: campaign_session_messages campaign_session_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_session_messages
    ADD CONSTRAINT campaign_session_messages_pkey PRIMARY KEY (id);


--
-- Name: campaign_session_notes campaign_session_notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_session_notes
    ADD CONSTRAINT campaign_session_notes_pkey PRIMARY KEY (session_id);


--
-- Name: campaign_sessions campaign_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_sessions
    ADD CONSTRAINT campaign_sessions_pkey PRIMARY KEY (id);


--
-- Name: campaigns campaigns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_pkey PRIMARY KEY (id);


--
-- Name: combat_encounters combat_encounters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_encounters
    ADD CONSTRAINT combat_encounters_pkey PRIMARY KEY (id);


--
-- Name: combat_participants combat_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_participants
    ADD CONSTRAINT combat_participants_pkey PRIMARY KEY (id);


--
-- Name: dice_rolls dice_rolls_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dice_rolls
    ADD CONSTRAINT dice_rolls_pkey PRIMARY KEY (id);


--
-- Name: dm_conversation_members dm_conversation_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dm_conversation_members
    ADD CONSTRAINT dm_conversation_members_pkey PRIMARY KEY (conversation_id, user_id);


--
-- Name: dm_conversations dm_conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dm_conversations
    ADD CONSTRAINT dm_conversations_pkey PRIMARY KEY (id);


--
-- Name: dm_message_attachments dm_message_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dm_message_attachments
    ADD CONSTRAINT dm_message_attachments_pkey PRIMARY KEY (id);


--
-- Name: dm_messages dm_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dm_messages
    ADD CONSTRAINT dm_messages_pkey PRIMARY KEY (id);


--
-- Name: friend_requests friend_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friend_requests
    ADD CONSTRAINT friend_requests_pkey PRIMARY KEY (id);


--
-- Name: friendships friendships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT friendships_pkey PRIMARY KEY (user_id, friend_user_id);


--
-- Name: generator_definitions generator_definitions_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generator_definitions
    ADD CONSTRAINT generator_definitions_code_key UNIQUE (code);


--
-- Name: generator_definitions generator_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generator_definitions
    ADD CONSTRAINT generator_definitions_pkey PRIMARY KEY (id);


--
-- Name: generator_field_definitions generator_field_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generator_field_definitions
    ADD CONSTRAINT generator_field_definitions_pkey PRIMARY KEY (id);


--
-- Name: generator_pools generator_pools_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generator_pools
    ADD CONSTRAINT generator_pools_pkey PRIMARY KEY (id);


--
-- Name: generator_results generator_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generator_results
    ADD CONSTRAINT generator_results_pkey PRIMARY KEY (id);


--
-- Name: generator_variants generator_variants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generator_variants
    ADD CONSTRAINT generator_variants_pkey PRIMARY KEY (id);


--
-- Name: glossary_terms glossary_terms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.glossary_terms
    ADD CONSTRAINT glossary_terms_pkey PRIMARY KEY (id);


--
-- Name: initiative_entries initiative_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.initiative_entries
    ADD CONSTRAINT initiative_entries_pkey PRIMARY KEY (id);


--
-- Name: initiative_queues initiative_queues_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.initiative_queues
    ADD CONSTRAINT initiative_queues_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: player_characters player_characters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_characters
    ADD CONSTRAINT player_characters_pkey PRIMARY KEY (id);


--
-- Name: rules_pages rules_pages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rules_pages
    ADD CONSTRAINT rules_pages_pkey PRIMARY KEY (id);


--
-- Name: session_live_state session_live_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_live_state
    ADD CONSTRAINT session_live_state_pkey PRIMARY KEY (id);


--
-- Name: session_player_notes session_player_notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_player_notes
    ADD CONSTRAINT session_player_notes_pkey PRIMARY KEY (id);


--
-- Name: session_live_state uq_session_live_state_session; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_live_state
    ADD CONSTRAINT uq_session_live_state_session UNIQUE (session_id);


--
-- Name: session_player_notes uq_session_player_notes_session_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_player_notes
    ADD CONSTRAINT uq_session_player_notes_session_user UNIQUE (session_id, user_id);


--
-- Name: user_blocks user_blocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_blocks
    ADD CONSTRAINT user_blocks_pkey PRIMARY KEY (blocker_user_id, blocked_user_id);


--
-- Name: user_campaign_favorites user_campaign_favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_campaign_favorites
    ADD CONSTRAINT user_campaign_favorites_pkey PRIMARY KEY (user_id, campaign_id);


--
-- Name: user_notes user_notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notes
    ADD CONSTRAINT user_notes_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: campaign_characters ux_campaign_characters_campaign_character; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_characters
    ADD CONSTRAINT ux_campaign_characters_campaign_character UNIQUE (campaign_id, character_id);


--
-- Name: generator_field_definitions ux_generator_field_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generator_field_definitions
    ADD CONSTRAINT ux_generator_field_key UNIQUE (variant_id, field_key);


--
-- Name: generator_variants ux_generator_variant_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generator_variants
    ADD CONSTRAINT ux_generator_variant_code UNIQUE (generator_definition_id, variant_code);


--
-- Name: glossary_terms ux_glossary_term_pl_system; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.glossary_terms
    ADD CONSTRAINT ux_glossary_term_pl_system UNIQUE (term_pl, system);


--
-- Name: idx_campaign_characters_campaign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_characters_campaign ON public.campaign_characters USING btree (campaign_id);


--
-- Name: idx_campaign_characters_campaign_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_characters_campaign_id ON public.campaign_characters USING btree (campaign_id);


--
-- Name: idx_campaign_characters_character; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_characters_character ON public.campaign_characters USING btree (character_id);


--
-- Name: idx_campaign_characters_character_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_characters_character_id ON public.campaign_characters USING btree (character_id);


--
-- Name: idx_campaign_characters_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_characters_user_id ON public.campaign_characters USING btree (user_id);


--
-- Name: idx_campaign_materials_campaign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_materials_campaign ON public.campaign_materials USING btree (campaign_id, created_at DESC);


--
-- Name: idx_campaign_notifications_user_campaign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_notifications_user_campaign ON public.campaign_notifications USING btree (user_id, campaign_id, created_at DESC);


--
-- Name: idx_campaign_player_notes_campaign_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_player_notes_campaign_id ON public.campaign_player_notes USING btree (campaign_id);


--
-- Name: idx_campaign_player_notes_updated_at_desc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_player_notes_updated_at_desc ON public.campaign_player_notes USING btree (updated_at DESC);


--
-- Name: idx_campaign_player_notes_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_player_notes_user_id ON public.campaign_player_notes USING btree (user_id);


--
-- Name: idx_campaign_session_attendance_campaign_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_session_attendance_campaign_id ON public.campaign_session_attendance USING btree (campaign_id);


--
-- Name: idx_campaign_session_attendance_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_session_attendance_session_id ON public.campaign_session_attendance USING btree (session_id);


--
-- Name: idx_campaign_session_attendance_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_session_attendance_status ON public.campaign_session_attendance USING btree (status);


--
-- Name: idx_campaign_session_attendance_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_session_attendance_user_id ON public.campaign_session_attendance USING btree (user_id);


--
-- Name: idx_campaign_session_messages_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_session_messages_session ON public.campaign_session_messages USING btree (session_id, created_at);


--
-- Name: idx_campaign_sessions_campaign; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaign_sessions_campaign ON public.campaign_sessions USING btree (campaign_id, created_at DESC);


--
-- Name: idx_campaigns_owner_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaigns_owner_created ON public.campaigns USING btree (owner_user_id, created_at DESC);


--
-- Name: idx_campaigns_visibility_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_campaigns_visibility_updated ON public.campaigns USING btree (visibility, updated_at DESC);


--
-- Name: idx_combat_encounters_campaign_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_combat_encounters_campaign_id ON public.combat_encounters USING btree (campaign_id);


--
-- Name: idx_combat_encounters_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_combat_encounters_session_id ON public.combat_encounters USING btree (session_id);


--
-- Name: idx_combat_participants_character_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_combat_participants_character_id ON public.combat_participants USING btree (character_id);


--
-- Name: idx_combat_participants_encounter_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_combat_participants_encounter_id ON public.combat_participants USING btree (encounter_id);


--
-- Name: idx_dice_rolls_campaign_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dice_rolls_campaign_created_at ON public.dice_rolls USING btree (campaign_id, created_at DESC);


--
-- Name: idx_dice_rolls_character_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dice_rolls_character_created_at ON public.dice_rolls USING btree (character_id, created_at DESC);


--
-- Name: idx_dice_rolls_encounter_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dice_rolls_encounter_created_at ON public.dice_rolls USING btree (encounter_id, created_at DESC);


--
-- Name: idx_dice_rolls_rolled_by_user_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dice_rolls_rolled_by_user_created_at ON public.dice_rolls USING btree (rolled_by_user_id, created_at DESC);


--
-- Name: idx_dice_rolls_session_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dice_rolls_session_created_at ON public.dice_rolls USING btree (session_id, created_at DESC);


--
-- Name: idx_dm_attachments_message; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dm_attachments_message ON public.dm_message_attachments USING btree (message_id, id);


--
-- Name: idx_dm_conversations_last_message; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dm_conversations_last_message ON public.dm_conversations USING btree (last_message_at DESC, updated_at DESC);


--
-- Name: idx_dm_members_user_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dm_members_user_status ON public.dm_conversation_members USING btree (user_id, status, joined_at DESC);


--
-- Name: idx_dm_messages_conversation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dm_messages_conversation ON public.dm_messages USING btree (conversation_id, id DESC);


--
-- Name: idx_friend_requests_receiver_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_friend_requests_receiver_status ON public.friend_requests USING btree (receiver_user_id, status, created_at DESC);


--
-- Name: idx_friend_requests_sender_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_friend_requests_sender_status ON public.friend_requests USING btree (sender_user_id, status, created_at DESC);


--
-- Name: idx_friendships_friend_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_friendships_friend_user ON public.friendships USING btree (friend_user_id);


--
-- Name: idx_glossary_system_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_glossary_system_category ON public.glossary_terms USING btree (system, category);


--
-- Name: idx_init_campaign_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_init_campaign_updated ON public.initiative_queues USING btree (campaign_id, updated_at DESC);


--
-- Name: idx_init_entries_queue_entity_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_init_entries_queue_entity_type ON public.initiative_entries USING btree (queue_id, entity_type);


--
-- Name: idx_init_entries_queue_sort; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_init_entries_queue_sort ON public.initiative_entries USING btree (queue_id, sort_order, initiative DESC, created_at);


--
-- Name: idx_init_owner_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_init_owner_created ON public.initiative_queues USING btree (owner_user_id, created_at DESC);


--
-- Name: idx_password_reset_tokens_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_password_reset_tokens_expires_at ON public.password_reset_tokens USING btree (expires_at);


--
-- Name: idx_password_reset_tokens_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_password_reset_tokens_user_id ON public.password_reset_tokens USING btree (user_id);


--
-- Name: idx_player_characters_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_player_characters_owner ON public.player_characters USING btree (owner_user_id);


--
-- Name: idx_player_characters_system; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_player_characters_system ON public.player_characters USING btree (system_code);


--
-- Name: idx_session_live_state_active_encounter_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_live_state_active_encounter_id ON public.session_live_state USING btree (active_encounter_id);


--
-- Name: idx_session_live_state_campaign_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_live_state_campaign_id ON public.session_live_state USING btree (campaign_id);


--
-- Name: idx_session_live_state_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_live_state_session_id ON public.session_live_state USING btree (session_id);


--
-- Name: idx_session_player_notes_campaign_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_player_notes_campaign_id ON public.session_player_notes USING btree (campaign_id);


--
-- Name: idx_session_player_notes_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_player_notes_session_id ON public.session_player_notes USING btree (session_id);


--
-- Name: idx_session_player_notes_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_player_notes_user_id ON public.session_player_notes USING btree (user_id);


--
-- Name: idx_user_blocks_blocked; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_blocks_blocked ON public.user_blocks USING btree (blocked_user_id);


--
-- Name: idx_user_campaign_favorites_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_campaign_favorites_user_created ON public.user_campaign_favorites USING btree (user_id, created_at DESC);


--
-- Name: idx_user_notes_campaign_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_notes_campaign_id ON public.user_notes USING btree (campaign_id);


--
-- Name: idx_user_notes_character_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_notes_character_id ON public.user_notes USING btree (character_id);


--
-- Name: idx_user_notes_user_updated_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_notes_user_updated_at ON public.user_notes USING btree (user_id, updated_at DESC);


--
-- Name: idx_users_display_name_lower; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_display_name_lower ON public.users USING btree (lower((display_name)::text));


--
-- Name: idx_users_username_lower; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_username_lower ON public.users USING btree (lower((username)::text));


--
-- Name: ix_generator_results_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_generator_results_created_at ON public.generator_results USING btree (created_at DESC);


--
-- Name: ux_campaigns_join_code_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_campaigns_join_code_active ON public.campaigns USING btree (join_code) WHERE (deleted_at IS NULL);


--
-- Name: ux_dm_conversations_direct_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_dm_conversations_direct_key ON public.dm_conversations USING btree (direct_key) WHERE (direct_key IS NOT NULL);


--
-- Name: ux_friend_requests_pending_pair; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_friend_requests_pending_pair ON public.friend_requests USING btree (sender_user_id, receiver_user_id, status);


--
-- Name: ux_generator_pool_type_system_subtype; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_generator_pool_type_system_subtype ON public.generator_pools USING btree (generator_type, system_code, subtype);


--
-- Name: ux_rules_pages_system_slug; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_rules_pages_system_slug ON public.rules_pages USING btree (system_code, slug);


--
-- Name: ux_users_username_tag; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_users_username_tag ON public.users USING btree (username, tag_code);


--
-- Name: campaign_characters campaign_characters_campaign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_characters
    ADD CONSTRAINT campaign_characters_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;


--
-- Name: campaign_characters campaign_characters_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_characters
    ADD CONSTRAINT campaign_characters_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: campaign_materials campaign_materials_campaign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_materials
    ADD CONSTRAINT campaign_materials_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;


--
-- Name: campaign_materials campaign_materials_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_materials
    ADD CONSTRAINT campaign_materials_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: campaign_members campaign_members_campaign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_members
    ADD CONSTRAINT campaign_members_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;


--
-- Name: campaign_members campaign_members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_members
    ADD CONSTRAINT campaign_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: campaign_notifications campaign_notifications_campaign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_notifications
    ADD CONSTRAINT campaign_notifications_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;


--
-- Name: campaign_notifications campaign_notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_notifications
    ADD CONSTRAINT campaign_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: campaign_player_notes campaign_player_notes_campaign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_player_notes
    ADD CONSTRAINT campaign_player_notes_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;


--
-- Name: campaign_player_notes campaign_player_notes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_player_notes
    ADD CONSTRAINT campaign_player_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: campaign_session_attendance campaign_session_attendance_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_session_attendance
    ADD CONSTRAINT campaign_session_attendance_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.campaign_sessions(id) ON DELETE CASCADE;


--
-- Name: campaign_session_attendance campaign_session_attendance_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_session_attendance
    ADD CONSTRAINT campaign_session_attendance_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: campaign_session_messages campaign_session_messages_author_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_session_messages
    ADD CONSTRAINT campaign_session_messages_author_user_id_fkey FOREIGN KEY (author_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: campaign_session_messages campaign_session_messages_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_session_messages
    ADD CONSTRAINT campaign_session_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.campaign_sessions(id) ON DELETE CASCADE;


--
-- Name: campaign_session_notes campaign_session_notes_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_session_notes
    ADD CONSTRAINT campaign_session_notes_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.campaign_sessions(id) ON DELETE CASCADE;


--
-- Name: campaign_session_notes campaign_session_notes_updated_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_session_notes
    ADD CONSTRAINT campaign_session_notes_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: campaign_sessions campaign_sessions_campaign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_sessions
    ADD CONSTRAINT campaign_sessions_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;


--
-- Name: campaign_sessions campaign_sessions_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_sessions
    ADD CONSTRAINT campaign_sessions_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: campaigns campaigns_owner_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: combat_encounters combat_encounters_campaign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_encounters
    ADD CONSTRAINT combat_encounters_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;


--
-- Name: combat_encounters combat_encounters_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_encounters
    ADD CONSTRAINT combat_encounters_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id);


--
-- Name: combat_encounters combat_encounters_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_encounters
    ADD CONSTRAINT combat_encounters_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.campaign_sessions(id) ON DELETE SET NULL;


--
-- Name: combat_participants combat_participants_character_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_participants
    ADD CONSTRAINT combat_participants_character_id_fkey FOREIGN KEY (character_id) REFERENCES public.player_characters(id) ON DELETE SET NULL;


--
-- Name: combat_participants combat_participants_encounter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_participants
    ADD CONSTRAINT combat_participants_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.combat_encounters(id) ON DELETE CASCADE;


--
-- Name: dice_rolls dice_rolls_campaign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dice_rolls
    ADD CONSTRAINT dice_rolls_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;


--
-- Name: dice_rolls dice_rolls_character_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dice_rolls
    ADD CONSTRAINT dice_rolls_character_id_fkey FOREIGN KEY (character_id) REFERENCES public.player_characters(id) ON DELETE SET NULL;


--
-- Name: dice_rolls dice_rolls_encounter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dice_rolls
    ADD CONSTRAINT dice_rolls_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.combat_encounters(id) ON DELETE SET NULL;


--
-- Name: dice_rolls dice_rolls_participant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dice_rolls
    ADD CONSTRAINT dice_rolls_participant_id_fkey FOREIGN KEY (participant_id) REFERENCES public.combat_participants(id) ON DELETE SET NULL;


--
-- Name: dice_rolls dice_rolls_rolled_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dice_rolls
    ADD CONSTRAINT dice_rolls_rolled_by_user_id_fkey FOREIGN KEY (rolled_by_user_id) REFERENCES public.users(id);


--
-- Name: dice_rolls dice_rolls_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dice_rolls
    ADD CONSTRAINT dice_rolls_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.campaign_sessions(id) ON DELETE SET NULL;


--
-- Name: dm_conversation_members dm_conversation_members_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dm_conversation_members
    ADD CONSTRAINT dm_conversation_members_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.dm_conversations(id) ON DELETE CASCADE;


--
-- Name: dm_conversation_members dm_conversation_members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dm_conversation_members
    ADD CONSTRAINT dm_conversation_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: dm_conversations dm_conversations_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dm_conversations
    ADD CONSTRAINT dm_conversations_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: dm_conversations dm_conversations_last_message_sender_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dm_conversations
    ADD CONSTRAINT dm_conversations_last_message_sender_user_id_fkey FOREIGN KEY (last_message_sender_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: dm_message_attachments dm_message_attachments_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dm_message_attachments
    ADD CONSTRAINT dm_message_attachments_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.dm_messages(id) ON DELETE CASCADE;


--
-- Name: dm_message_attachments dm_message_attachments_uploader_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dm_message_attachments
    ADD CONSTRAINT dm_message_attachments_uploader_user_id_fkey FOREIGN KEY (uploader_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: dm_messages dm_messages_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dm_messages
    ADD CONSTRAINT dm_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.dm_conversations(id) ON DELETE CASCADE;


--
-- Name: dm_messages dm_messages_sender_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dm_messages
    ADD CONSTRAINT dm_messages_sender_user_id_fkey FOREIGN KEY (sender_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: campaign_characters fk_campaign_characters_player_character; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_characters
    ADD CONSTRAINT fk_campaign_characters_player_character FOREIGN KEY (character_id) REFERENCES public.player_characters(id) ON DELETE CASCADE;


--
-- Name: campaign_session_attendance fk_campaign_session_attendance_campaign; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_session_attendance
    ADD CONSTRAINT fk_campaign_session_attendance_campaign FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;


--
-- Name: friend_requests friend_requests_receiver_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friend_requests
    ADD CONSTRAINT friend_requests_receiver_user_id_fkey FOREIGN KEY (receiver_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: friend_requests friend_requests_sender_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friend_requests
    ADD CONSTRAINT friend_requests_sender_user_id_fkey FOREIGN KEY (sender_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: friendships friendships_friend_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT friendships_friend_user_id_fkey FOREIGN KEY (friend_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: friendships friendships_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT friendships_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: generator_field_definitions generator_field_definitions_variant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generator_field_definitions
    ADD CONSTRAINT generator_field_definitions_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.generator_variants(id) ON DELETE CASCADE;


--
-- Name: generator_variants generator_variants_generator_definition_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generator_variants
    ADD CONSTRAINT generator_variants_generator_definition_id_fkey FOREIGN KEY (generator_definition_id) REFERENCES public.generator_definitions(id) ON DELETE CASCADE;


--
-- Name: initiative_entries initiative_entries_queue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.initiative_entries
    ADD CONSTRAINT initiative_entries_queue_id_fkey FOREIGN KEY (queue_id) REFERENCES public.initiative_queues(id) ON DELETE CASCADE;


--
-- Name: initiative_queues initiative_queues_campaign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.initiative_queues
    ADD CONSTRAINT initiative_queues_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE SET NULL;


--
-- Name: initiative_queues initiative_queues_owner_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.initiative_queues
    ADD CONSTRAINT initiative_queues_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: password_reset_tokens password_reset_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: player_characters player_characters_owner_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_characters
    ADD CONSTRAINT player_characters_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: session_live_state session_live_state_active_encounter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_live_state
    ADD CONSTRAINT session_live_state_active_encounter_id_fkey FOREIGN KEY (active_encounter_id) REFERENCES public.combat_encounters(id) ON DELETE SET NULL;


--
-- Name: session_live_state session_live_state_campaign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_live_state
    ADD CONSTRAINT session_live_state_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;


--
-- Name: session_live_state session_live_state_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_live_state
    ADD CONSTRAINT session_live_state_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.campaign_sessions(id) ON DELETE CASCADE;


--
-- Name: session_live_state session_live_state_updated_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_live_state
    ADD CONSTRAINT session_live_state_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: session_player_notes session_player_notes_campaign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_player_notes
    ADD CONSTRAINT session_player_notes_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;


--
-- Name: session_player_notes session_player_notes_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_player_notes
    ADD CONSTRAINT session_player_notes_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.campaign_sessions(id) ON DELETE CASCADE;


--
-- Name: session_player_notes session_player_notes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_player_notes
    ADD CONSTRAINT session_player_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_blocks user_blocks_blocked_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_blocks
    ADD CONSTRAINT user_blocks_blocked_user_id_fkey FOREIGN KEY (blocked_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_blocks user_blocks_blocker_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_blocks
    ADD CONSTRAINT user_blocks_blocker_user_id_fkey FOREIGN KEY (blocker_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_campaign_favorites user_campaign_favorites_campaign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_campaign_favorites
    ADD CONSTRAINT user_campaign_favorites_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;


--
-- Name: user_campaign_favorites user_campaign_favorites_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_campaign_favorites
    ADD CONSTRAINT user_campaign_favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_notes user_notes_campaign_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notes
    ADD CONSTRAINT user_notes_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE SET NULL;


--
-- Name: user_notes user_notes_character_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notes
    ADD CONSTRAINT user_notes_character_id_fkey FOREIGN KEY (character_id) REFERENCES public.player_characters(id) ON DELETE SET NULL;


--
-- Name: user_notes user_notes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notes
    ADD CONSTRAINT user_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


