CREATE TABLE dice_rolls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    session_id BIGINT REFERENCES campaign_sessions(id) ON DELETE SET NULL,
    encounter_id BIGINT REFERENCES combat_encounters(id) ON DELETE SET NULL,
    participant_id BIGINT REFERENCES combat_participants(id) ON DELETE SET NULL,
    character_id BIGINT REFERENCES player_characters(id) ON DELETE SET NULL,
    rolled_by_user_id BIGINT NOT NULL REFERENCES users(id),
    roll_label VARCHAR(160),
    roll_expression VARCHAR(120) NOT NULL,
    roll_type VARCHAR(40) NOT NULL DEFAULT 'GENERIC',
    total INT NOT NULL,
    dice_results TEXT NOT NULL,
    modifier INT NOT NULL DEFAULT 0,
    is_private BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT dice_rolls_roll_type_check CHECK (roll_type IN ('GENERIC', 'ATTACK', 'DAMAGE', 'SAVE', 'SKILL', 'INITIATIVE', 'CUSTOM'))
);

CREATE INDEX idx_dice_rolls_campaign_created_at ON dice_rolls(campaign_id, created_at DESC);
CREATE INDEX idx_dice_rolls_session_created_at ON dice_rolls(session_id, created_at DESC);
CREATE INDEX idx_dice_rolls_encounter_created_at ON dice_rolls(encounter_id, created_at DESC);
CREATE INDEX idx_dice_rolls_character_created_at ON dice_rolls(character_id, created_at DESC);
CREATE INDEX idx_dice_rolls_rolled_by_user_created_at ON dice_rolls(rolled_by_user_id, created_at DESC);
