CREATE TABLE session_live_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    session_id BIGINT NOT NULL REFERENCES campaign_sessions(id) ON DELETE CASCADE,
    scene_title VARCHAR(160),
    scene_image_url TEXT,
    scene_description TEXT,
    active_encounter_id BIGINT REFERENCES combat_encounters(id) ON DELETE SET NULL,
    updated_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_session_live_state_session UNIQUE (session_id)
);

CREATE INDEX idx_session_live_state_campaign_id ON session_live_state (campaign_id);
CREATE INDEX idx_session_live_state_session_id ON session_live_state (session_id);
CREATE INDEX idx_session_live_state_active_encounter_id ON session_live_state (active_encounter_id);
