ALTER TABLE campaign_session_attendance
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

UPDATE campaign_session_attendance
SET status = CASE UPPER(status)
    WHEN 'YES' THEN 'AVAILABLE'
    WHEN 'NO' THEN 'UNAVAILABLE'
    WHEN 'MAYBE' THEN 'MAYBE'
    ELSE 'MAYBE'
END;

ALTER TABLE campaign_session_attendance
    ADD COLUMN IF NOT EXISTS campaign_id BIGINT;

UPDATE campaign_session_attendance attendance
SET campaign_id = session.campaign_id
FROM campaign_sessions session
WHERE session.id = attendance.session_id
  AND attendance.campaign_id IS NULL;

ALTER TABLE campaign_session_attendance
    ALTER COLUMN campaign_id SET NOT NULL;

ALTER TABLE campaign_session_attendance
    ADD CONSTRAINT fk_campaign_session_attendance_campaign
        FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE;

ALTER TABLE campaign_session_attendance
    ADD COLUMN IF NOT EXISTS note TEXT;

ALTER TABLE campaign_session_attendance
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE campaign_session_attendance
    DROP CONSTRAINT IF EXISTS campaign_session_attendance_pkey;

ALTER TABLE campaign_session_attendance
    ADD CONSTRAINT campaign_session_attendance_pk PRIMARY KEY (id);

ALTER TABLE campaign_session_attendance
    ADD CONSTRAINT campaign_session_attendance_session_user_unique UNIQUE (session_id, user_id);

ALTER TABLE campaign_session_attendance
    ADD CONSTRAINT campaign_session_attendance_status_check
        CHECK (status IN ('AVAILABLE', 'MAYBE', 'UNAVAILABLE'));

CREATE INDEX IF NOT EXISTS idx_campaign_session_attendance_campaign_id
    ON campaign_session_attendance(campaign_id);

CREATE INDEX IF NOT EXISTS idx_campaign_session_attendance_session_id
    ON campaign_session_attendance(session_id);

CREATE INDEX IF NOT EXISTS idx_campaign_session_attendance_user_id
    ON campaign_session_attendance(user_id);

CREATE INDEX IF NOT EXISTS idx_campaign_session_attendance_status
    ON campaign_session_attendance(status);
