CREATE TABLE IF NOT EXISTS campaign_player_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id BIGINT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(160) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_campaign_player_notes_campaign_id
  ON campaign_player_notes(campaign_id);

CREATE INDEX IF NOT EXISTS idx_campaign_player_notes_user_id
  ON campaign_player_notes(user_id);

CREATE INDEX IF NOT EXISTS idx_campaign_player_notes_updated_at_desc
  ON campaign_player_notes(updated_at DESC);
