CREATE TABLE IF NOT EXISTS requested_rolls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id BIGINT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  session_id BIGINT NOT NULL REFERENCES campaign_sessions(id) ON DELETE CASCADE,
  target_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  target_character_id BIGINT REFERENCES player_characters(id) ON DELETE SET NULL,
  requested_by_user_id BIGINT NOT NULL REFERENCES users(id),
  fulfilled_roll_id BIGINT REFERENCES dice_rolls(id) ON DELETE SET NULL,
  roll_label VARCHAR(160) NOT NULL,
  roll_type VARCHAR(40) NOT NULL DEFAULT 'SKILL',
  roll_expression VARCHAR(120),
  ability_key VARCHAR(80),
  skill_key VARCHAR(80),
  dc INT,
  is_dc_hidden BOOLEAN NOT NULL DEFAULT TRUE,
  show_success_to_player BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  CONSTRAINT requested_rolls_status_check CHECK (status IN ('PENDING', 'FULFILLED', 'CANCELLED')),
  CONSTRAINT requested_rolls_dc_check CHECK (dc IS NULL OR dc >= 0)
);

CREATE INDEX IF NOT EXISTS idx_requested_rolls_campaign_id ON requested_rolls(campaign_id);
CREATE INDEX IF NOT EXISTS idx_requested_rolls_session_id ON requested_rolls(session_id);
CREATE INDEX IF NOT EXISTS idx_requested_rolls_target_user_id ON requested_rolls(target_user_id);
CREATE INDEX IF NOT EXISTS idx_requested_rolls_target_character_id ON requested_rolls(target_character_id);
CREATE INDEX IF NOT EXISTS idx_requested_rolls_requested_by_user_id ON requested_rolls(requested_by_user_id);
CREATE INDEX IF NOT EXISTS idx_requested_rolls_status ON requested_rolls(status);
CREATE INDEX IF NOT EXISTS idx_requested_rolls_created_at_desc ON requested_rolls(created_at DESC);
