CREATE TABLE IF NOT EXISTS session_player_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id BIGINT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  session_id BIGINT NOT NULL REFERENCES campaign_sessions(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(120) NOT NULL DEFAULT '',
  content TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_session_player_notes_session_user UNIQUE (session_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_session_player_notes_session_id
  ON session_player_notes(session_id);

CREATE INDEX IF NOT EXISTS idx_session_player_notes_user_id
  ON session_player_notes(user_id);

CREATE INDEX IF NOT EXISTS idx_session_player_notes_campaign_id
  ON session_player_notes(campaign_id);
