UPDATE generator_pools
SET payload_json = '{
  "givenNames": ["Alaric","Mira","Thorin","Selene","Varis","Eldrin","Kaela","Brom","Isolde","Darian","Runa","Tavian","Liora","Kest","Nadia","Oren","Sana","Marek","Irena","Tomasz"],
  "familyNames": ["Blackwood","Ravencrest","Stormhill","Duskfall","Ironvale","Moonbrook","Ashford","Voss","Kowal","Ward","Koss","Marzec","Quell","Ren","Pax","Morra","Hale","Lenz","Sowa","Brant"],
  "roles": ["Straznik","Kupiec","Kaplan","Najemnik","Skryba","Zwiadowca","Medyk","Bibliotekarz","Mechanik","Przemytnik","Dyplomata","Kartograf","Archiwista","Patolog","Reporter","Medium","Celnik","Herold","Lowca relikwii","Radiooperator"],
  "personalities": ["uprzejmy, ale ostrozny","podejrzliwy i konkretny","porywczy pod presja","spokojny obserwator","tajemniczy i oszczedny w slowach","arogancki wobec slabosci","serdeczny dla starych znajomych","chlodny profesjonalista","nerwowy, gdy ktos pyta o przeszlosc","zgryzliwy, ale pomocny","lojalny po zawarciu umowy","ambitny i cierpliwy","przesadnie formalny","sarkastyczny w stresie","milczacy przy obcych","opiekunczy wobec slabszych","metodyczny do przesady","latwo wpada w gniew","ukrywa strach zartami","pamieta kazda przysluge"],
  "motivations": ["splaca stary dlug","szuka zaginionej osoby","chroni swoja dzielnice","pragnie awansu","ukrywa klatwe albo chorobe","zbiera pieniadze na wykup","poluje na zdrajce","chce odzyskac honor rodu","prowadzi nielegalny interes","boi sie nadchodzacej wojny","chce zatrzec blad sprzed lat","pilnuje cudzego sekretu","szuka patrona","ucieka przed prawem","chce ocalic reputacje","testuje lojalnosc druzyny","szuka mapy albo dokumentu","odgrywa role dla kogos poteznego","chce opuscic miasto","musi dostarczyc wiadomosc"],
  "appearances": ["znoszony plaszcz i czujne spojrzenie","drogi dodatek przy prostym stroju","rece przyzwyczajone do pracy","blizna ukrywana pod kolnierzem","notatnik pelny poprawek","buty z innego regionu","srebrny sygnet bez herbu","zmeczona twarz i pewny glos","torba z narzedziami","ubranie pachnace dymem","stare okulary w metalowej oprawie","rekawiczki noszone nawet w cieple","amulet schowany pod koszula","twarz osoby, ktora malo spi","nienaturalnie czyste dlonie","plaszcz z zaszyta kieszenia","wlosy przyciete nozem","zbyt wiele kluczy przy pasie","ubranie z wojskowego demobilu","spokojne ruchy i nerwowe oczy"],
  "secrets": ["zna prawdziwego winnego","pracuje dla rywala","ma fałszywe nazwisko","ukryl dowod w bezpiecznym miejscu","wie o drugim wejsciu","zdradzil kogos bliskiego","jest szantazowany","chroni osobe poszukiwana","ma dlog wobec frakcji","widzial cos niemozliwego","sprzedal informacje dwa razy","boi sie jednego symbolu","zna haslo do zamknietej czesci miasta","jest ostatnim swiadkiem sprawy","udaje nizszy status","ukrywa chorobe","dostal rozkaz milczenia","ma przy sobie cudzy list","zna lokalna trase ucieczki","nie jest tym, za kogo sie podaje"],
  "hooks": ["prosi o rozmowe po zmroku","rozpoznaje przedmiot druzyny","zna skrot do waznego miejsca","potrzebuje ochrony na jedna noc","ma list, ktorego nie powinien miec","oferuje prace bez zadawania pytan","znika zaraz po spotkaniu","wskazuje falszywy trop z dobrego powodu","chce wymienic sekret za przysluge","jest obserwowany przez kogos z tlumu","przypadkiem zdradza wazna date","płaci stara moneta","zostawia znak na stole","ma mape bez legendy","szuka kogos podobnego do jednego z bohaterow","prosi o odzyskanie paczki","twierdzi, ze zna przyszly problem","ma ranę, ktorej nie chce wyjasnic","wzywa druzynę do miejsca publicznego","zostawia ostrzezenie zamiast nagrody"]
}'::jsonb,
updated_at = now()
WHERE generator_type = 'npc' AND system_code = 'any' AND subtype = 'general.quick';

UPDATE generator_pools
SET payload_json = '{
  "types": ["Tawerna","Sklep","Osada","Dzielnica","Swiatynia","Biblioteka","Port","Las","Ruiny","Zamek","Wieza maga","Cmentarz","Most","Kopalnia","Mlyn","Sad","Laboratorium","Posterunek","Archiwum","Targ"],
  "namePrefixes": ["Czarny","Srebrny","Zielony","Stary","Cichy","Mokry","Zlamany","Kruczy","Bialy","Czerwony","Zloty","Kamienny","Solny","Mglisty","Pusty","Trzeci","Ostatni","Suchy","Wilczy","Zardzewialy"],
  "nameNouns": ["Kogut","Latarnia","Trakt","Dzwon","Most","Archiwum","Studnia","Jar","Brama","Mlot","Klucz","Pył","Szczyt","Mur","Port","Rynek","Szyb","Dom","Korytarz","Sanktuarium"],
  "exteriors": ["niski budynek z cieplym swiatlem","fasada pelna starych napraw","brama pilnowana bardziej niz powinna","szyld starty przez deszcz","okna zasloniete nierownymi deskami","mur z nowsza latka","dziedziniec z jednym pustym miejscem","wejscie pachnace dymem","schody starta od wielu stop","drzwi z niepasujacym zamkiem","kamienny prog z wyrytym znakiem","zadaszenie trzeszczace na wietrze","latarnia palaca sie za dnia","puste skrzynie przy wejsciu","sciana z dawnym herbem","brudne okno z czystym odciskiem","zawalony bok i nowe podpory","tablica ogloszen bez dat","furtka otwierana od srodka","dach latany skora i blacha"],
  "interiors": ["waske przejscia i za duzo cieni","jedno pomieszczenie zamkniete na nowy zamek","zapach ziol, wilgoci i starego drewna","stoly ustawione tak, by widziec drzwi","polki z pustym miejscem po czyms waznym","podloga skrzypi tylko w jednym punkcie","piec wygaszony mimo zimna","mapa bez nazw na scianie","korytarz konczy sie zbyt szybko","schody prowadza pod podloge","zegar stoi na jednej godzinie","sufit ma swieze slady dymu","lustro odwrocone do sciany","dywan przykrywa metalowy właz","półmrok ukrywa boczna wnękę","papiery ulozone zbyt rowno","drzwi wewnetrzne bez klamki","ławka z wyrytym symbolem","nisza z resztka kadzidla","skrzynia przykuta do belki"],
  "atmospheres": ["cieplo, ale nerwowo","cicho az do przesady","gwar maskuje wazne slowa","wilgotno i ciezko","swobodnie tylko na pierwszy rzut oka","ludzie patrza zbyt krotko","miejsce pachnie kurzem i tajemnica","kazdy zna tu cudze sprawy","nikt nie chce mowic pierwszy","bezpiecznie, dopoki nie pada nazwisko","w powietrzu czuc stary dym","cisza przychodzi falami","rozmowy urywaja sie przy drzwiach","slychac odlegla prace metalu","zwykly ruch kryje napiecie","jeden stol jest zawsze pusty","zapach deszczu bez deszczu","światło wydaje się za blade","kroki niosa sie za daleko","miejsce czeka na decyzje"],
  "npcs": ["zmeczony wlasciciel","milczaca strazniczka","nadmiernie uprzejmy skryba","dziecko znajace za duzo","podrozny z zakrwawionym rekawem","kupiec liczacy cudze monety","kaplan unikajacy spojrzen","rzemieslnik z ukrytym warsztatem","poslaniec bez znaku","kobieta pilnujaca bocznych drzwi","stary zolnierz przy oknie","urzędnik z podwojnym rejestrem","uczen niosacy zamknieta skrzynke","medyk proszacy o cisze","szuler z karta w rekawie","przewoznik bez lodzi","archiwistka z popiolem na palcach","gospodarz udajacy spokój","strażnik mostu po służbie","czlowiek, ktory czeka na zle nazwisko"],
  "hooks": ["ktos prosi o dyskretna pomoc","wazna osoba znika po wejsciu","pod podloga znaleziono starszy znak","lokalny konflikt ma wybuchnac dzis","towar lub dokument jest podmieniony","jedno pomieszczenie nie istnieje na planie","ktos wraca tu po nocy","drzwi otwieraja sie tylko dla jednej osoby","na miejscu zostaje cudza pieczec","plotka prowadzi do realnego problemu","właściciel zna sekret graczy","zapas ma zniknac przed switem","mapa wskazuje inne wejscie","swiadek chce mowic tylko tutaj","ktoś zostawia monete jako znak","patrol omija to miejsce","stara umowa wraca do zycia","ktoś falszuje kolejke zdarzen","miejsce ma zbyt dobra ochrone","wezwanie przychodzi z zamknietego pokoju"],
  "hazards": ["slaby strop","ukryta pulapka","zatrute jedzenie","podejrzany ogien","mokre schody","zawalone przejscie","fałszywa podloga","strażnik na cudzym żołdzie","stary mechanizm","niestabilny mostek","pyl powodujacy kaszel","ciemny zaulek bez wyjscia","zly zapach maskujacy trucizne","przewod elektryczny lub magiczny","pękający lód","ukryty obserwator","hałas przyciagajacy wrogów","chory zwierz w środku","drzwi ryglowane od zewnatrz","znak, ktory uruchamia alarm"],
  "secrets": ["piwnica jest wieksza niz budynek","wlasciciel placi za milczenie","najstarsza czesc ma innego pana","pod miejscem biegnie tunel","jeden pokoj jest kopia innego","dokumenty maja podwojne daty","mieszkańcy znaja stary rytual","zaginiony gosc nadal tu jest","mapa celowo klamie","lokalny autorytet ma ukryte wejscie","stary dług chroni to miejsce","symbol na murze jest świeży","najbezpieczniejsze drzwi prowadza do problemu","jedna osoba nigdy stad nie wychodzi","schowek zawiera cudze nazwisko","krzyki tlumaczy się rurami","każdy wie o sekrecie poza nowymi","zegar odmierza cudzy termin","właściwy klucz jest bezużyteczny bez hasła","miejsce nalezy do kogoś martwego"]
}'::jsonb,
updated_at = now()
WHERE generator_type = 'location' AND system_code = 'any' AND subtype = 'general.quick';

UPDATE generator_pools
SET payload_json = '{
  "types": ["Gildia","Zakon","Rada","Kult","Kompania","Cech","Bractwo","Rod","Krag","Liga","Fundacja","Korporacja","Kartel","Klan","Milicja","Karawana","Towarzystwo","Komitet","Syndykat","Siec"],
  "adjectives": ["Srebrna","Cicha","Zielona","Zelazna","Biala","Czarna","Ostatnia","Trzecia","Ukryta","Wolna","Stara","Nowa","Miedziana","Krucza","Sucha","Północna","Złamana","Wysoka","Nocna","Czerwona"],
  "nouns": ["Brama","Pieczec","Latarnia","Studnia","Mapa","Dlon","Przysiega","Droga","Igla","Waga","Korona","Skrzynia","Rada","Wieza","Siec","Karawana","Księga","Zasłona","Kotwica","Iskra"],
  "symbols": ["klucz bez zebow","oko w trojkacie","srebrna nić","zlamany mlot","czarna świeca","pusty herb","kropla wody","kruk na wadze","trzy kreski","maskowana dlon","zardzewialy znak","biały sznur","moneta bez twarzy","otwarta księga","zielona latarnia","czerwony stempel","zębate koło","pęknięta korona","zakryte lustro","gwiazda pod kreską"],
  "leaders": ["publiczny przewodniczacy","ukryty patron","rada trzech osob","charyzmatyczny lider","czlowiek oficjalnie martwy","mlody dziedzic","stary skarbnik","bezimienny poslaniec","kaplan z podwojna funkcja","byly najemnik","archiwistka z wpływami","glos przez radio","komitet bez podpisow","sędzia z prywatna straza","lekarz bez licencji","kupiec od dlugów","kapitan karawany","program decyzyjny","rodzina wlascicieli","prorok od codziennych spraw"],
  "goals": ["kontrolowac informacje","odnalezc relikt","obalic moznego","powstrzymac rytual","utrzymac monopol","zabezpieczyc szlak","ukryc katastrofe","przejac dokumenty","kupic cudzy dlug","ochronic lidera","zniszczyc rywala","wymusic nowy podatek","przetrwac zime","zdobyc patronat","przejac port","zamknac sledztwo","zatrzymac uciekiniera","wygrac spór bez walki","zdobyc technologie","utrzymac pozory normalnosci"],
  "resources": ["informatorzy","pieniadze","bezpieczne kryjowki","dostep do dokumentow","uzbrojeni ludzie","stary magazyn","sieć kurierow","wplyw w urzedzie","sekretne przejscie","radio lub kod","lekarstwa","konie albo pojazdy","warsztat","archiwum","falszywe pieczecie","drony albo zwiadowcy","dlugi wdziecznosci","zapas wody","mapy","czlowiek w strazy"],
  "secrets": ["lider pracuje dla rywala","fundamentem jest falszywe prawo","najwiekszy wrog byl zalozycielem","przysiega wlasnie wygasa","czlonkowie ukryli zamach","rytual juz sie nie udal","prawdziwy lider nie zyje","agent jest kopia","kontrakt podpisano po katastrofie","zasob konczy sie szybciej niz mowia","trasa zostala sprzedana","wewnetrzna frakcja planuje bunt","symbol pochodzi od wroga","czlonek zostawia wskazowki","siedziba jest przyneta","najlepszy atut jest bezuzyteczny","ksiegi maja drugi rejestr","organizacja splatuje cudzy dlug","wrog chroni ich przed czyms gorszym","sekret zna osoba spoza struktur"],
  "relations": ["walczy z lokalna wladza","udaje sojusznika rywala","jest potrzebna mieszkancom","wisi dlug wobec swiatyni","ma pakt z kupcami","szantazuje straz","chroni biednych za cene lojalnosci","rywalizuje z cechem","kupuje przychylnosc mediow","utrzymuje pokoj z przemocy","zalezy od jednego szlaku","boi sie zewnetrznej kontroli","wykorzystuje cudzy konflikt","ma ukrytego patrona","jest rozbita na dwie frakcje","przekupuje urzednikow","wspiera bunt, ktory moze przegrac","pilnuje tajemnicy rodziny","jest narzedziem wiekszej sily","potrzebuje druzyny jako neutralnych posrednikow"]
}'::jsonb,
updated_at = now()
WHERE generator_type = 'faction' AND system_code = 'any' AND subtype = 'general.quick';

UPDATE generator_pools
SET payload_json = '{
  "temperatura": ["mrozno","chlodno","rzesko","lagodnie","cieplo","upalnie","duszno","nietypowo zimno","nietypowo cieplo","zmiennie","suche zimno","wilgotne cieplo","parno","ostro po nocy","cieplo po deszczu","zimno przy ziemi","goraco w sloncu","lodowaty poranek","cieply wieczor","temperatura spada"],
  "opady": ["drobny deszcz","sucho","snieg z deszczem","krotka ulewa","mżawka","grad","gesty snieg","cieply deszcz","mgielna wilgoc","opad pyłu","marznacy deszcz","burzowa sciana wody","przelotny kapusniak","wilgotna zawiesina","rosa jak po deszczu","brak opadow po burzy","mokry snieg","deszcz na horyzoncie","ciężkie chmury bez opadu","opad zaczyna sie za chwile"],
  "wiatr": ["silny boczny wiatr","prawie bezwietrznie","zimne podmuchy","porywisty wiatr","lekki wiatr","wiatr od wody","suchy wiatr","cieply podmuch","zmienny kierunek","cisza przed burza","wiatr z pyłem","ostre szkwały","wiatr w koronach drzew","niski przeciag","wiatr niesie zapach dymu","gwałtowne porywy","wiatr cichnie nagle","staly wiatr w plecy","wiatr utrudnia rozmowe","wiatr niesie odlegle dzwieki"],
  "zachmurzenie": ["bezchmurnie","czesciowe zachmurzenie","niskie chmury","ciezkie chmury","rwany front","blade slonce","ciemny horyzont","wysokie cienkie chmury","niebo jak olow","przerwy w chmurach","chmury burzowe","szybko przesuwane pasma","mleczne niebo","szary strop","czyste niebo po burzy","chmury przy ziemi","ciemna smuga na zachodzie","jasne okno w chmurach","czerwony zachod przez chmury","niebo bez glebi"],
  "widoczność": ["dobra","ograniczona mgla","slaba przez deszcz","czysta po wietrze","migotanie od upalu","ciemno przed burza","jasno i ostro","snieg zaslania dystans","kurz w powietrzu","wilgotna poswiata","dym na horyzoncie","nocna przejrzystosc","mgla przy ziemi","ostre kontrasty","deszcz zaciera slady","swiatlo odbija sie od mokrego kamienia","ciemne cienie pod chmurami","dal znika za opadem","latarnie widac za pozno","horyzont jest podejrzanie blisko"]
}'::jsonb,
updated_at = now()
WHERE generator_type = 'weather' AND system_code = 'any' AND subtype = 'default';
