UPDATE generator_pools
SET payload_json = $json$
{
  "gems": [
    {"name": "polerowany agat", "value": 10},
    {"name": "blekitny kwarc", "value": 10},
    {"name": "malachitowa plytka", "value": 10},
    {"name": "krysztal gorski", "value": 25},
    {"name": "ciemny onyks", "value": 25},
    {"name": "perla rzeczna", "value": 25},
    {"name": "granat w srebrnej oprawie", "value": 50},
    {"name": "topaz miodowy", "value": 50},
    {"name": "ametyst z inkluzja", "value": 50},
    {"name": "jadeitowy paciorek", "value": 75},
    {"name": "turkusowy kaboszon", "value": 75},
    {"name": "opal mleczny", "value": 100},
    {"name": "szafir z rysa", "value": 250},
    {"name": "rubin z czarnym punktem", "value": 250},
    {"name": "szmaragd woskowany", "value": 250},
    {"name": "diamentowy okruch", "value": 500},
    {"name": "perla czarna", "value": 500},
    {"name": "gwiezdny szafir", "value": 750},
    {"name": "krwawy rubin", "value": 1000},
    {"name": "diament bez skazy", "value": 1500}
  ],
  "artObjects": [
    {"name": "srebrna lyzeczka z herbem", "value": 25},
    {"name": "miniatura portretowa w miedzi", "value": 25},
    {"name": "rzez biony grzebien z kosci", "value": 25},
    {"name": "bransoleta z zielonego szkla", "value": 50},
    {"name": "emaliowana brosza", "value": 50},
    {"name": "modlitewnik w skorzanej oprawie", "value": 50},
    {"name": "srebrny kielich z wgniotka", "value": 75},
    {"name": "lakowana kasetka", "value": 75},
    {"name": "figurka sokola z brazu", "value": 100},
    {"name": "haftowany pas dworski", "value": 100},
    {"name": "zloty pierscien z pieczecia", "value": 250},
    {"name": "statuetka swietego z jaspisu", "value": 250},
    {"name": "lusterko w zloconej ramie", "value": 250},
    {"name": "mapa na jedwabiu", "value": 500},
    {"name": "misa ceremonialna", "value": 500},
    {"name": "korona teatralna z prawdziwymi perelkami", "value": 750},
    {"name": "ikona w srebrze", "value": 750},
    {"name": "sztylet paradny z kamieniami", "value": 1000},
    {"name": "zegar podrozny mistrza", "value": 1000},
    {"name": "zloty medalion dynastyczny", "value": 1500}
  ],
  "magicItems": {
    "common": [
      "Latarnia wiecznie ciepla",
      "Kamien suchego ogniska",
      "Kubek zawsze chlodnej wody",
      "Igla trafiajaca w nawlekanie",
      "Plaszcz bez kurzu",
      "Butelka jednego szeptu",
      "Kreda niegasnacego znaku",
      "Guzik powrotu do kieszeni",
      "Lyzka dobrego smaku",
      "Kosc do gry mrugajaca przy szostce",
      "Sakwa bez zapachu",
      "Pioro piszace pod dyktando",
      "Moneta wracajaca do dloni",
      "Rzemien cichego wiazania",
      "Zapalnik bez iskry",
      "Kompas do najblizszej karczmy",
      "Pieczec prawdziwego podpisu",
      "Koralik lekkiego snu",
      "Chusta suchego czola",
      "Dzwoneczek widocznego progu"
    ],
    "uncommon": [
      "Pierscien cichego kroku",
      "Amulet jednego ostrzezenia",
      "Rdzawy klucz do przypadkowych zamkow",
      "Lina sama szukajaca zaczepu",
      "Rekawice pewnego chwytu",
      "Okulary tropiciela atramentu",
      "Buty krotkiego skoku",
      "Sztylet powracajacy do pochwy",
      "Koc odporny na plomien",
      "Maska spokojnego oddechu",
      "Fiolka pamietajaca zapach",
      "Torba bez dna na drobiazgi",
      "Bransoleta cichego alarmu",
      "Kamien tlumionego glosu",
      "Lusterko ostatniej twarzy",
      "Pas noszenia ciezaru",
      "Kaptur lekkiej mgly",
      "Kielich wykrywania trucizny",
      "Gwizde k przywolania wierzchowca",
      "Mapa pokazujaca droge powrotna"
    ],
    "rare": [
      "Ostrze srebrnego echa",
      "Plaszcz mglistego kroku",
      "Kostur zamknietego przejscia",
      "Amulet cudzego cienia",
      "Pierscien jednej prawdy",
      "Latarnia widzaca niewidzialne",
      "Tarcza odbitego slowa",
      "Buty podniebnego biegu",
      "Pas sily starego rodu",
      "Krysztal przechowanego zaklecia",
      "Luk ciszy po strzale",
      "Flet usypiajacej melodii",
      "Rog odwagi kompanii",
      "Szata niewidocznej nici",
      "Klejnot skradzionego snu",
      "Rekawica chwytania pocisku",
      "Korona lagodnego rozkazu",
      "Zbroja lekkiego kroku",
      "Ksiega jednej odpowiedzi",
      "Pierscien wezwania sojusznika"
    ],
    "veryRare": [
      "Miecz burzowego sladu",
      "Zwierciadlo drugiej drogi",
      "Pancerz nocnego straznika",
      "Berlo zlamanej przysiegi",
      "Kostur trzech bram",
      "Plaszcz lotu bez skrzydel",
      "Amulet zatrzymanej rany",
      "Pierscien oddalonego glosu",
      "Kielich wskrzeszonej pamieci",
      "Luk gwiezdnej ciwy",
      "Tarcza sadu przodkow",
      "Krysztal burzy w kieszeni",
      "Hełm widzenia zamiaru",
      "Rog wezwania armii cieni",
      "Szata przejscia przez mur",
      "Zegar cofajacy jeden oddech",
      "Korona bezimiennego wladcy",
      "Laska przemiany drogi",
      "Serce golemowego straznika",
      "Ksiezycowy klucz do sanktuarium"
    ],
    "legendary": [
      "Korona Siedmiu Przysiag",
      "Ostrze Ostatniego Switu",
      "Kielich Wiecznego Powrotu",
      "Pierscien Bezimiennego Krola",
      "Ksiega Zamknietych Er",
      "Lanca Gwiezdnej Bramy",
      "Tarcza Pierwszego Muru",
      "Plaszcz Nocy Bez Konca",
      "Berlo Ciszy po Wojnie",
      "Amulet Serca Burzy",
      "Zegar Utraconej Godziny",
      "Korona Morza Bez Brzegu",
      "Mlot Fundamentu Swiata",
      "Luk Dnia Sadu",
      "Krysztal Ostatniego Imienia",
      "Maska Proroka bez Twarzy",
      "Szata Drogi Miedzy Sferami",
      "Klucz do Zamku Ktorego Nie Ma",
      "Rog Wezwania Dawnych Bohaterow",
      "Oko Spiacego Smoka"
    ]
  },
  "mundaneItems": [
    "pek zelaznych kluczy",
    "mapa lokalnej okolicy",
    "zapieczetowany list",
    "kosciane kosci do gry",
    "fiolka atramentu",
    "kompas z peknietym szklem",
    "maly notes z dlugami",
    "zapasowy noz kuchenny",
    "woskowana sakiewka z ziolami",
    "zwitek cienkiej linki",
    "miedziana igielnica",
    "zlamana pieczec urzedowa",
    "para rekawic roboczych",
    "pudelko kredy i wegla",
    "skorzany pasek z klamra",
    "drewniany gwizdek straznika",
    "suchy prowiant na jeden dzien",
    "stary medalik bez lancuszka",
    "notatka z lista imion",
    "pusty flakon po perfumach"
  ],
  "containers": [
    "w ciezkiej skrzyni",
    "w workach pod luzna deska",
    "w glinianych dzbanach",
    "w falszywym dnie kufra",
    "rozsypany wsrod kosci",
    "w zamknietej kasetce z mosiadzu",
    "w skorzanej tubie",
    "w beczce pod warstwa soli",
    "w metalowym sejfie bez drzwiczek",
    "w rozcietym materacu",
    "w pudle po swiecach",
    "w sakwach na martwym mule",
    "w skrzynce przykrytej popiolem",
    "w pustej barylce po winie",
    "w kamiennym sarkofagu",
    "w drewnianej figurze",
    "w plecaku porzuconym przy ognisku",
    "w worku zszytym od srodka",
    "w szkatułce owiniętej plotnem",
    "w zelaznej klatce na dokumenty"
  ],
  "hidingPlaces": [
    "za ruchomym kamieniem",
    "pod posadzka",
    "w niszy za gobelinem",
    "w kominie starego paleniska",
    "w sekretnym schowku stolu",
    "wsrod rupieci, ktore wygladaja bezwartosciowo",
    "pod warstwa starego zboza",
    "za obluzowana cegla",
    "w belce stropowej",
    "pod plyta grobowa",
    "w pustej studni",
    "za falszywa sciana szafy",
    "w podwojnym dnie wozu",
    "w dziupli przy trakcie",
    "w kieszeni starego plaszcza",
    "pod siedziskiem lawy",
    "w oprawie duzej ksiegi",
    "w wyschnietym wiadrze",
    "pod sterta mokrych lin",
    "w ukrytej przegrodzie tarczy"
  ],
  "quirks": [
    "na dnie lezy inicjal poprzedniego wlasciciela",
    "jedna moneta jest wyraznie starsza od reszty",
    "skarb pachnie ozonem",
    "ktos niedawno zabral najcenniejszy przedmiot",
    "w srodku ukryto krotka grozbe",
    "po otwarciu slychac cichy klik mechanizmu",
    "monety sa ulozone wedlug dat",
    "wszystko owinięto tym samym zielonym sznurkiem",
    "na wieku widac slady paznokci",
    "przedmioty sa podejrzanie czyste",
    "wewnatrz lezy cudzy sygnet",
    "skrytka byla otwierana bardzo niedawno",
    "najmniejszy przedmiot jest najciezszy",
    "zapach kadzidla utrzymuje sie mimo wilgoci",
    "na papierze zostal odcisk pieczeci",
    "metal jest cieply w dotyku",
    "jeden przedmiot cicho brzeczy",
    "w rogu lezy zasuszony kwiat",
    "wszystko spisano na malej karteczce",
    "pojemnik ma drugi, pusty schowek"
  ]
}
$json$
WHERE generator_type = 'loot'
  AND system_code = 'dnd'
  AND subtype = 'default';
