CREATE TABLE IF NOT EXISTS user_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(120) NOT NULL,
  type VARCHAR(20) NOT NULL,
  content TEXT NOT NULL DEFAULT '',
  campaign_id BIGINT REFERENCES campaigns(id) ON DELETE SET NULL,
  character_id BIGINT REFERENCES player_characters(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_user_notes_type
    CHECK (type IN ('SESSION', 'NPC', 'ITEM', 'LORE', 'QUEST', 'OTHER'))
);

CREATE INDEX IF NOT EXISTS idx_user_notes_user_updated_at
  ON user_notes(user_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_notes_campaign_id
  ON user_notes(campaign_id);

CREATE INDEX IF NOT EXISTS idx_user_notes_character_id
  ON user_notes(character_id);
